//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoadTestProject
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using Microsoft.VisualStudio.TestTools.WebTesting;
    using Microsoft.VisualStudio.TestTools.WebTesting.Rules;


    public class CpuSamlingTestCoded : WebTest
    {

        public CpuSamlingTestCoded()
        {
            this.PreAuthenticate = true;
        }

        public override IEnumerator<WebTestRequest> GetRequestEnumerator()
        {
            // Initialize validation rules that apply to all requests in the WebTest
            if ((this.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.Low))
            {
                ValidateResponseUrl validationRule1 = new ValidateResponseUrl();
                this.ValidateResponse += new EventHandler<ValidationEventArgs>(validationRule1.Validate);
            }
            if ((this.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.Low))
            {
                ValidationRuleResponseTimeGoal validationRule2 = new ValidationRuleResponseTimeGoal();
                validationRule2.Tolerance = 0D;
                this.ValidateResponseOnPageComplete += new EventHandler<ValidationEventArgs>(validationRule2.Validate);
            }

            WebTestRequest request1 = new WebTestRequest("http://localhost:5974/");
            request1.ThinkTime = 1;
            yield return request1;
            request1 = null;

            WebTestRequest request2 = new WebTestRequest("http://localhost:5974/Home/About");
            request2.ThinkTime = 1;
            yield return request2;
            request2 = null;

            WebTestRequest request3 = new WebTestRequest("http://localhost:5974/Home/Contact");
            request3.ThinkTime = 1;
            yield return request3;
            request3 = null;

            WebTestRequest request4 = new WebTestRequest("http://localhost:5974/Account/Register");
            request4.ThinkTime = 1;
            yield return request4;
            request4 = null;

            WebTestRequest request5 = new WebTestRequest("http://localhost:5974/Account/Login");
            request5.ThinkTime = 10;
            yield return request5;
            request5 = null;

            WebTestRequest request6 = new WebTestRequest("http://localhost:5974/Account/Register");
            request6.ThinkTime = 8;
            request6.Method = "POST";
            FormPostHttpBody request6Body = new FormPostHttpBody();
            request6Body.FormPostParameters.Add("__RequestVerificationToken", "t0KZHRwvwF7sK0M3j4uB2gSR542AA3RRhhUYlngBGovu3tnFTvLNYCiKEPrfxHEefoAJ3sKmroc1PxSRn" +
                    "4p7D5nRe-K6avTrJ-ynJB1DukM1");
            request6Body.FormPostParameters.Add("UserName", "hello");
            request6Body.FormPostParameters.Add("Password", "100000");
            request6Body.FormPostParameters.Add("ConfirmPassword", "100000");
            request6.Body = request6Body;
            yield return request6;
            request6 = null;

            WebTestRequest request7 = new WebTestRequest("http://localhost:5974/Account/Login");
            request7.Method = "POST";
            request7.ExpectedResponseUrl = "http://localhost:5974/";
            FormPostHttpBody request7Body = new FormPostHttpBody();
            request7Body.FormPostParameters.Add("__RequestVerificationToken", "-JK9v7uiId0fWh_aD2fnPWoJp5hwDmK-B8cP75beo_PiWKicb68aIUDw1MeROe_XPTnSAzsaccNxfACYx" +
                    "nrDUFawf2FMJ3ui-R4tAO7Q_DE1");
            request7Body.FormPostParameters.Add("UserName", "hello");
            request7Body.FormPostParameters.Add("Password", "1000000");
            request7Body.FormPostParameters.Add("RememberMe", "false");
            request7.Body = request7Body;
            yield return request7;
            request7 = null;
        }
    }
}
